export const API_BASE_URL = 'http://localhost:5236';

// export const API_BASE_URL = 'https://backend-production-574e.up.railway.app';

export const API_ROUTES = {
  login: `${API_BASE_URL}/api/auth/login`,
  changePassword: `${API_BASE_URL}/api/auth/change-password`,
  companiesMe: `${API_BASE_URL}/api/companies/me`,
  dashboard: `${API_BASE_URL}/api/dashboard`,
  employees: `${API_BASE_URL}/api/employees`,
  // Employee module (EmployeeController)
  employeeBase: `${API_BASE_URL}/api/employee`,
  employeeDetail: (id: number) => `${API_BASE_URL}/api/employee/detail/${id}`,
  employeeByCompany: (compId: number) => `${API_BASE_URL}/api/employee/${compId}`,
  employeeUpdate: (id: number) => `${API_BASE_URL}/api/employee/${id}`,
  employeeDelete: (id: number) => `${API_BASE_URL}/api/employee/${id}`,
  employeeStatus: (id: number) => `${API_BASE_URL}/api/employee/status/${id}`,
  employeeToggle: (id: number) => `${API_BASE_URL}/api/employee/${id}/toggle-active`,
  employeeSearch: `${API_BASE_URL}/api/employee/search`,
  employeeUploadDoc: `${API_BASE_URL}/api/employee/upload-document`,
  employeeDocuments: (empId: number) => `${API_BASE_URL}/api/employee/documents/${empId}`,
  // Department & Designation
  departmentByCompany: (compId: number) => `${API_BASE_URL}/api/department/${compId}`,
  designationByCompany: (compId: number) => `${API_BASE_URL}/api/designation/${compId}`,
  attendanceImport: `${API_BASE_URL}/api/attendance/import`,
  attendanceReport: `${API_BASE_URL}/api/attendance/report`,
  leaveApply: `${API_BASE_URL}/api/leave/apply`,
  leaveApprove: `${API_BASE_URL}/api/leave/approve`,
  payrollRun: `${API_BASE_URL}/api/payroll/run`,
  payrollRegister: `${API_BASE_URL}/api/payroll/register`,
  payrollItems: (payrollId: number) => `${API_BASE_URL}/api/payroll/items/${payrollId}`,
  payrollReport: `${API_BASE_URL}/api/payroll/report`,
  reportsAttendance: `${API_BASE_URL}/api/reports/attendance`,
  reportsMonthlyAttendance: `${API_BASE_URL}/api/reports/attendance-monthly`,
  reportsPayrollRegister: `${API_BASE_URL}/api/reports/payroll-register`,
  reportsEmployeeMaster: `${API_BASE_URL}/api/reports/employee-master`,
  reportsLeaveRegister: `${API_BASE_URL}/api/reports/leave-register`,
  reportsReimbursementRegister: `${API_BASE_URL}/api/reports/reimbursement-register`,
  reportsLeaveBalance: `${API_BASE_URL}/api/reports/leave-balance`,
  reportsGratuity: `${API_BASE_URL}/api/reports/gratuity`,
  reportsProbation: `${API_BASE_URL}/api/reports/probation`,
  reportsDocumentExpiry: `${API_BASE_URL}/api/reports/document-expiry`,
  reportsEmployeeStatistics: `${API_BASE_URL}/api/reports/employee-statistics`,
  reportsLeaveStatistics: `${API_BASE_URL}/api/reports/leave-statistics`,
  reportsPayrollStatistics: `${API_BASE_URL}/api/reports/payroll-statistics`,
  reportsAssetRegister: `${API_BASE_URL}/api/reports/asset-register`,
  reportsAssetAllocation: `${API_BASE_URL}/api/reports/asset-allocation`,
  reportsAssetSummary: `${API_BASE_URL}/api/reports/asset-summary`,
  assetBase: `${API_BASE_URL}/api/assets`,
  adminSettings: `${API_BASE_URL}/api/admin/settings`,
  // aiChat: `${API_BASE_URL}/api/ai/chat`,
  aiChat: `${API_BASE_URL}/api/agent/chat`,
} as const;

